# Amazon Web Scraping

In [1]:
#Import Libraries

import pandas as pd # Imports the pandas library for data manipulation and analysis, aliasing it as 'pd' for convenience
import csv # Import the csv library to enable reading and writing CSV files
from bs4 import BeautifulSoup # Used for parsing HTML and extracting data from the website
import requests # Allows us to send HTTP requests to connect to the website
import time # Helps handle time-related tasks, like pausing the script (sleep)
import datetime # Used to get the current date and time for timestamping our data

import smtplib # Used for sending emails (specifically for price drop alerts)

In [2]:
# Connecting to Website and pull in data

URL = 'https://www.amazon.com/dp/B01JHD9E1Q' # The target website URL we want to scrape data from

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    
    "Accept-Language": "en-US,en;q=0.9",
    
    "Cookie": "i18n-prefs=USD; lc-main=en_US",
    
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Referer": "https://www.google.com/",
    "Upgrade-Insecure-Requests": "1",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "cross-site",
    "Sec-Fetch-User": "?1"
} # Headers are used to mimic a real browser (like Chrome) so Amazon doesn't detect us as a bot and block the request
 
page = requests.get(URL, headers=headers) # Connect to the website and fetch the page content

soup1 = BeautifulSoup(page.content, "html.parser") # Create a BeautifulSoup object to parse the raw HTML content

soup2 = BeautifulSoup(soup1.prettify(), "html.parser") # Re-parse the HTML to format it nicely (prettify) making it easier to search through

title = soup2.find(id='productTitle').get_text() # Find the HTML element with id 'productTitle' and extract the text inside it

price = soup2.find('span', class_='aok-offscreen').get_text() # Find the hidden price element using the class 'aok-offscreen'
price = price.split('with')[0] # Clean the price data: Split the text at 'with' to remove discount info and keep only the price

print(title)

print(price)

                 Well, That's Not A Good Sign Stick Figure Graphic Novelty Sarcastic Funny Tshirt


                 $14.99

In [3]:
# Clean up the data a little bit

title = title.strip() # Clean from spaces

price = price.strip()[1:] # Clean from spaces and removing $

print(title)

print(price)

Well, That's Not A Good Sign Stick Figure Graphic Novelty Sarcastic Funny Tshirt
14.99

In [4]:
# Create a Timestamp for your output to track when data was collected

today = datetime.date.today() # Get the current date using the datetime library

print(today)

2026-01-25

In [5]:
# Create CSV and write headers and data into the file

header = ['Product', 'Price', 'Date'] # Define the column headers for our dataset

data = [title, price, today] # Create a list containing the actual data we scraped to be written into the file

with open('Amazon Web Scraping.csv', 'w', newline='', encoding='UTF8') as f:
# Open a new CSV file named 'Amazon Web Scraping.csv' in write mode ('w')
# newline='' prevents empty lines between rows, and encoding='UTF8' ensures special characters are saved correctly
    writer = csv.writer(f) # Create a csv writer object to insert data into the file
    writer.writerow(header) # Write the header row (Title, Price, Date) as the first line
    writer.writerow(data) # Write the initial data row collected from the website

In [6]:
df = pd.read_csv(r"F:\Courses\Data Analysis\Data Analyst Bootcamp\Python\Projects\Amazon Web Scraping\Amazon Web Scraping.csv")

df

                                             Product  Price        Date
0  Well, That's Not A Good Sign Stick Figure Grap...  14.99  2026-01-25

In [7]:
# Appending data to the csv

with open('Amazon Web Scraping.csv', 'a+', newline='', encoding='UTF8') as f:
    # Open the CSV file in 'append' mode ('a+')
    writer = csv.writer(f)
    writer.writerow(data)

In [ ]:
# Combine all of the above code into one function

def check_price():
    URL = 'https://www.amazon.com/dp/B01JHD9E1Q' 

    headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Cookie": "i18n-prefs=USD; lc-main=en_US",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Referer": "https://www.google.com/",
    "Upgrade-Insecure-Requests": "1",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "cross-site",
    "Sec-Fetch-User": "?1"
    } 

    page = requests.get(URL, headers=headers) 
    soup1 = BeautifulSoup(page.content, "html.parser") 
    soup2 = BeautifulSoup(soup1.prettify(), "html.parser") 

    title = soup2.find(id='productTitle').get_text() 
    price = soup2.find('span', class_='aok-offscreen').get_text() 
    
    # Cleaning data
    price = price.split('with')[0] 
    title = title.strip() 
    price = price.strip()[1:] 
    
    today = datetime.date.today() 

    try:
        price_float = float(price)
    except ValueError:
        price_float = 0.0 

    header = ['Product', 'Price', 'Date'] 
    data = [title, price, today] 

    with open('Amazon Web Scraping.csv', 'a+', newline='', encoding='UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(data)
    
    if price_float < 12:
        send_mail()

In [ ]:
# Runs check_price after a set time and inputs data into your CSV

while(True): # Starts an infinite loop to run the script repeatedly without stopping
    check_price() # Calls the scraping function to fetch data and save it to the CSV
    time.sleep(86400) # Pauses execution for 86400 seconds (24 hours) before the next run

Email Sent Successfully!

In [23]:
df = pd.read_csv(r"F:\Courses\Data Analysis\Data Analyst Bootcamp\Python\Projects\Amazon Web Scraping\Amazon Web Scraping.csv")

df

                                             Product  Price        Date
0  Well, That's Not A Good Sign Stick Figure Grap...  14.99  2026-01-25
1  Well, That's Not A Good Sign Stick Figure Grap...  14.99  2026-01-25
2  Well, That's Not A Good Sign Stick Figure Grap...  14.99  2026-01-25

In [ ]:
# Sending yourself an email when a price hits below a certain level

def send_mail():
    server = smtplib.SMTP_SSL('smtp.gmail.com',465)
    server.ehlo()
    #server.starttls()
    server.ehlo()
    server.login('example@gmail.com','xxxxxxxxxxxxxxx')
    
    subject = "The Shirt you want is below $20! Now is your chance to buy!"
    body = "Mahmoud, This is the moment we have been waiting for. Now is your chance to pick up the shirt of your dreams. Don't mess it up! Link here: https://www.amazon.com/dp/B01JHD9E1Q"
   
    msg = f"Subject: {subject}\n\n{body}"
    
    server.sendmail(
        'exaaple@gmail.com', 'example@gmail.com',
        msg
     
    )
    print("Email Sent Successfully!") 
    server.quit()